CREATE TABLE CONTRACTOR(
    CONTRACTOR_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(16) NOT NULL,
    LAST_NAME VARCHAR(16) NOT NULL,
    PERSONAL_NUMBER CHAR(5) NOT NULL UNIQUE
);

CREATE SEQUENCE CONTRACTOR_SEQUENCE_ID START WITH 6;